language: node_js
node_js:
- "10"
install:
# - npm i
- cd vue
- npm i
script:
# - npm run build
- npm run build:gh-pages
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: vue/dist

